### ISSUE TITLE
Make fails in Ubuntu 18

### ISSUE THREAD

**Issue by norrinr** [osm/icka#8]
Ubuntu 18.. At first had to get flen (got from github) and websockets (got from apt) for golang.. Then this:

```
$ make
go build
# github.com/osm/flen
../go/src/github.com/osm/flen/flen.go:56:10: undefined: strings.ReplaceAll
../go/src/github.com/osm/flen/flen.go:69:45: undefined: strings.ReplaceAll
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by norrinr** [comment]
This works in Ubuntu 20..

```
$ make
go build
go: downloading github.com/osm/flen v1.0.0
go: downloading github.com/gorilla/websocket v1.4.2
go: extracting github.com/gorilla/websocket v1.4.2
go: extracting github.com/osm/flen v1.0.0
go: finding github.com/gorilla/websocket v1.4.2
go: finding github.com/osm/flen v1.0.0
$ file icka
icka: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=-Hh49HTXX8Oo90BnAQBr/BbyzHzaTsPgBMEGbRnI7/VgDbsbcfsHBvTnqCx-Qs/rnF2vxRGdtY35ygJ_ZnF, not stripped
```

**Comment by opiqbox** [comment]
i think it works in golang 1.14 or above
